CURRENCIES = [
    ["BTC", "BTC", "Bitcoin"],
    ["ETH", "ETH", "Ethereum"],
    ["LTC", "LTC", "Litecoin"],
    ["BCH", "BCH", "Bitcoin Cash"],
    ["ETC", "ETC", "Ethereum Classic"],
    ["ZRX", "ZRX", "0x Protocol"],
    ["USDC", "USDC", "USDC"],
    ["BAT", "BAT", "Basic Attention Token"],
    ["ZEC", "ZEC", "Zcash"],
    ["XRP", "XRP", "XRP"],
    ["XLM", "XLM", "Stellar Lumens"],
    ["REP", "REP", "Augur"],
    ["DAI", "DAI", "Dai"],
    ["LINK", "LINK", "Chainlink"],
    ["XTZ", "XTZ", "Tezos"],
    ["DASH", "DASH", "Dash"],
    ["OXT", "OXT", "Orchid"],
    ["ATOM", "ATOM", "Cosmos"],
    ["KNC", "KNC", "Kyber Network"],
    ["COMP", "COMP", "Compound"],
    ["ALGO", "ALGO", "Algorand"],
    ["BAND", "BAND", "Band Protocol"],
    ["NMR", "NMR", "Numeraire"],
    ["CGLD", "CGLD", "Celo"],
    ["UMA", "UMA", "UMA"],
    ["LRC", "LRC", "Loopring"],
    ["YFI", "YFI", "yearn.finance"],
    ["UNI", "UNI", "Uniswap"],
    ["BAL", "BAL", "Balancer"],
    ["CVC", "CVC", "Civic"],
    ["MANA", "MANA", "Decentraland"],
    ["DNT", "DNT", "district0x"],
    ["FIL", "FIL", "Filecoin"],
    ["AAVE", "AAVE", "Aave"],
    ["BNT", "BNT", "Bancor Network Token"],
    ["SNX", "SNX", "Synthetix Network Token"],
    ["GRT", "GRT", "The Graph"],
    ["SUSHI", "SUSHI", "SushiSwap"],
    ["SKL", "SKL", "SKALE"],
    ["ADA", "ADA", "Cardano"],
    ["STORJ", "STORJ", "Storj"],
    ["CRV", "CRV", "Curve DAO Token"],
    ["ANKR", "ANKR", "Ankr"],
    ["NKN", "NKN", "NKN"],
    ["OGN", "OGN", "Origin Token"],
    ["1INCH", "1INCH", "1inch"],
    ["FORTH", "FORTH", "Ampleforth Governance Token"],
    ["USDT", "USDT", "Tether"],
    ["CTSI", "CTSI", "Cartesi"],
    ["TRB", "TRB", "Tellor"],
    ["RLC", "RLC", "iExec RLC"],
    ["ICP", "ICP", "Internet Computer"],
    ["DOGE", "DOGE", "Dogecoin"],
    ["MLN", "MLN", "Enzyme"],
    ["GTC", "GTC", "Gitcoin"],
    ["AMP", "AMP", "Amp"],
    ["DOT", "DOT", "Polkadot"],
    ["SOL", "SOL", "Solana"],
    ["CHZ", "CHZ", "Chiliz"],
    ["LPT", "LPT", "Livepeer"],
    ["QNT", "QNT", "Quant"],
    ["MASK", "MASK", "Mask Network"],
    ["PAX", "PAX", "Paxos Standard"],
    ["FET", "FET", "Artificial Superintelligence Alliance"],
    ["FARM", "FARM", "Harvest Finance"],
    ["ACH", "ACH", "Alchemy Pay"],
    ["IOTX", "IOTX", "IoTeX"],
    ["REQ", "REQ", "Request"],
    ["AXS", "AXS", "Axie Infinity"],
    ["TRU", "TRU", "TrueFi"],
    ["COTI", "COTI", "COTI"],
    ["RAD", "RAD", "Radworks"],
    ["XYO", "XYO", "XYO"],
    ["BTRST", "BTRST", "Braintrust"],
    ["ZEN", "ZEN", "Horizen"],
    ["SHIB", "SHIB", "SHIBA INU"],
    ["AGLD", "AGLD", "Adventure Gold"],
    ["AVAX", "AVAX", "Avalanche"],
    ["RARI", "RARI", "Rarible"],
    ["BADGER", "BADGER", "Badger DAO"],
    ["JASMY", "JASMY", "Jasmy"],
    ["PERP", "PERP", "Perpetual Protocol"],
    ["ARPA", "ARPA", "ARPA Chain"],
    ["AUCTION", "AUCTION", "Bounce Token"],
    ["ASM", "ASM", "Assemble AI"],
    ["KRL", "KRL", "Kryll"],
    ["LCX", "LCX", "LCX"],
    ["TRAC", "TRAC", "OriginTrail"],
    ["CRO", "CRO", "Cronos"],
    ["SUKU", "SUKU", "SUKU"],
    ["ENS", "ENS", "Ethereum Name Service"],
    ["ALCX", "ALCX", "Alchemix"],
    ["POWR", "POWR", "Powerledger"],
    ["BICO", "BICO", "BICONOMY (BICO)"],
    ["FOX", "FOX", "Shapeshift FOX Token"],
    ["IDEX", "IDEX", "IDEX"],
    ["SPELL", "SPELL", "Spell Token"],
    ["SUPER", "SUPER", "SuperVerse"],
    ["POLS", "POLS", "Polkastarter"],
    ["API3", "API3", "Api3"],
    ["GODS", "GODS", "Gods Unchained"],
    ["BLZ", "BLZ", "Bluzelle"],
    ["MDT", "MDT", "Measurable Data Token"],
    ["IMX", "IMX", "Immutable"],
    ["GFI", "GFI", "Goldfinch Protocol"],
    ["LQTY", "LQTY", "Liquity"],
    ["PRO", "PRO", "Propy"],
    ["INV", "INV", "Inverse Finance"],
    ["NCT", "NCT", "PolySwarm"],
    ["STX", "STX", "Stacks"],
    ["SHPING", "SHPING", "SHPING"],
    ["CTX", "CTX", "Cryptex Finance"],
    ["PLU", "PLU", "Pluton"],
    ["DIA", "DIA", "DIA"],
    ["ORCA", "ORCA", "Orca"],
    ["FIDA", "FIDA", "Bonfida"],
    ["AVT", "AVT", "Aventus"],
    ["ALICE", "ALICE", "MyNeighborAlice"],
    ["AERGO", "AERGO", "Aergo"],
    ["AIOZ", "AIOZ", "AIOZ Network"],
    ["HIGH", "HIGH", "Highstreet"],
    ["GLM", "GLM", "Golem"],
    ["APE", "APE", "ApeCoin"],
    ["MINA", "MINA", "Mina"],
    ["ROSE", "ROSE", "Oasis Network"],
    ["GMT", "GMT", "STEPN"],
    ["GST", "GST", "Green Satoshi Token"],
    ["FLOW", "FLOW", "Flow"],
    ["SAND", "SAND", "The Sandbox"],
    ["OP", "OP", "Optimism"],
    ["KSM", "KSM", "Kusama"],
    ["C98", "C98", "Coin98"],
    ["INDEX", "INDEX", "Index Cooperative"],
    ["FORT", "FORT", "Forta"],
    ["POND", "POND", "Marlin"],
    ["FIS", "FIS", "StaFi"],
    ["ALEPH", "ALEPH", "Aleph Cloud"],
    ["MATH", "MATH", "MATH"],
    ["HOPR", "HOPR", "HOPR"],
    ["ELA", "ELA", "Elastos"],
    ["TIME", "TIME", "Chrono.tech"],
    ["DEXT", "DEXT", "DEXTools"],
    ["METIS", "METIS", "Metis"],
    ["XCN", "XCN", "Onyxcoin"],
    ["BOBA", "BOBA", "Boba Network"],
    ["AST", "AST", "AirSwap"],
    ["SWFTC", "SWFTC", "SwftCoin"],
    ["GNO", "GNO", "Gnosis"],
    ["ABT", "ABT", "Arcblock"],
    ["RARE", "RARE", "SuperRare"],
    ["STG", "STG", "Stargate Finance"],
    ["CELR", "CELR", "Celer Network"],
    ["CBETH", "CBETH", "Coinbase Wrapped Staked ETH"],
    ["NEAR", "NEAR", "NEAR Protocol"],
    ["AURORA", "AURORA", "Aurora"],
    ["CVX", "CVX", "Convex Finance"],
    ["OCEAN", "OCEAN", "Ocean Protocol"],
    ["PUNDIX", "PUNDIX", "Pundi X (New)"],
    ["INJ", "INJ", "Injective"],
    ["PNG", "PNG", "Pangolin"],
    ["00", "00", "00 Token"],
    ["ILV", "ILV", "Illuvium"],
    ["HBAR", "HBAR", "Hedera"],
    ["APT", "APT", "Aptos"],
    ["WAXL", "WAXL", "Wrapped Axelar"],
    ["MSOL", "MSOL", "Marinade Staked SOL"],
    ["MNDE", "MNDE", "Marinade"],
    ["HFT", "HFT", "Hashflow"],
    ["LDO", "LDO", "Lido DAO Token"],
    ["QI", "QI", "BENQI"],
    ["PYR", "PYR", "Vulcan Forged PYR"],
    ["GHST", "GHST", "Aavegotchi"],
    ["EGLD", "EGLD", "MultiversX"],
    ["MAGIC", "MAGIC", "MAGIC"],
    ["RPL", "RPL", "Rocket Pool"],
    ["KAVA", "KAVA", "Kava"],
    ["T", "T", "Threshold"],
    ["AUDIO", "AUDIO", "Audius"],
    ["AXL", "AXL", "Axelar"],
    ["VOXEL", "VOXEL", "Voxies"],
    ["BLUR", "BLUR", "Blur"],
    ["ACS", "ACS", "Access"],
    ["PRIME", "PRIME", "Echelon Prime"],
    ["LSETH", "LSETH", "Liquid Staked ETH"],
    ["ARB", "ARB", "Arbitrum"],
    ["FLR", "FLR", "Flare"],
    ["DIMO", "DIMO", "DIMO"],
    ["SPA", "SPA", "Sperax"],
    ["SUI", "SUI", "SUI"],
    ["OSMO", "OSMO", "Osmosis"],
    ["HNT", "HNT", "Helium"],
    ["SEI", "SEI", "Sei"],
    ["PYUSD", "PYUSD", "PayPal USD"],
    ["VET", "VET", "vechain"],
    ["VTHO", "VTHO", "VeThor Token"],
    ["VARA", "VARA", "Vara"],
    ["BIGTIME", "BIGTIME", "Big Time"],
    ["TIA", "TIA", "Celestia"],
    ["JTO", "JTO", "Jito"],
    ["SEAM", "SEAM", "Seamless"],
    ["BONK", "BONK", "Bonk"],
    ["HONEY", "HONEY", "Hivemapper"],
    ["ONDO", "ONDO", "Ondo"],
    ["ZETA", "ZETA", "Zetachain"],
    ["VELO", "VELO", "Velodrome Finance"],
    ["AERO", "AERO", "Aerodrome Finance"],
    ["RENDER", "RENDER", "Render"],
    ["STRK", "STRK", "Starknet Token"],
    ["AKT", "AKT", "Akash Network"],
    ["RONIN", "RONIN", "Ronin"],
    ["ARKM", "ARKM", "Arkham"],
    ["TNSR", "TNSR", "Tensor"],
    ["SHDW", "SHDW", "Shadow Token"],
    ["OMNI", "OMNI", "Omni Network"],
    ["KARRAT", "KARRAT", "Karrat"],
    ["SAFE", "SAFE", "Safe"],
    ["NEON", "NEON", "Neon EVM"],
    ["DRIFT", "DRIFT", "Drift Protocol"],
    ["PIRATE", "PIRATE", "Pirate Nation Token"],
    ["ZRO", "ZRO", "LayerZero"],
    ["EURC", "EURC", "EURC"],
    ["CORECHAIN", "CORECHAIN", "Core"],
    ["BLAST", "BLAST", "Blast"],
    ["A8", "A8", "Ancient8"],
    ["LRDS", "LRDS", "Blocklords"],
    ["SD", "SD", "Stader"],
    ["G", "G", "Gravity"],
    ["ACX", "ACX", "Across Protocol"],
    ["POL", "POL", "Polygon Ecosystem Token"],
    ["ALEO", "ALEO", "Aleo"],
    ["ZK", "ZK", "ZKsync"],
    ["COW", "COW", "CoW Protocol"],
    ["ZETACHAIN", "ZETACHAIN", "Zetachain"],
    ["WELL", "WELL", "Moonwell"],
    ["EIGEN", "EIGEN", "EigenCloud"],
    ["IO", "IO", "io.net"],
    ["DEGEN", "DEGEN", "Degen"],
    ["SWELL", "SWELL", "SWELL"],
    ["PEPE", "PEPE", "Pepe"],
    ["WIF", "WIF", "dogwifhat"],
    ["FLOKI", "FLOKI", "FLOKI"],
    ["MOODENG", "MOODENG", "Moo Deng"],
    ["MOG", "MOG", "Mog Coin"],
    ["ME", "ME", "Magic Eden"],
    ["GIGA", "GIGA", "Gigachad"],
    ["TURBO", "TURBO", "Turbo"],
    ["PRCL", "PRCL", "Parcl"],
    ["PNUT", "PNUT", "Peanut the Squirrel"],
    ["TRUMP", "TRUMP", "OFFICIAL TRUMP"],
    ["TOSHI", "TOSHI", "Toshi"],
    ["VVV", "VVV", "Venice Token"],
    ["ETHFI", "ETHFI", "ether.fi"],
    ["BERA", "BERA", "Berachain"],
    ["B3", "B3", "B3 (Base)"],
    ["IP", "IP", "Story"],
    ["PENGU", "PENGU", "Pudgy Penguins"],
    ["POPCAT", "POPCAT", "Popcat (SOL)"],
    ["TAO", "TAO", "Bittensor"],
    ["KAITO", "KAITO", "Kaito"],
    ["PYTH", "PYTH", "Pyth Network"],
    ["MORPHO", "MORPHO", "Morpho"],
    ["REZ", "REZ", "Renzo"],
    ["COOKIE", "COOKIE", "Cookie DAO"],
    ["RED", "RED", "Redstone"],
    ["ATH", "ATH", "Aethir"],
    ["SYRUP", "SYRUP", "Maple Finance"],
    ["FAI", "FAI", "Freysa"],
    ["L3", "L3", "Layer3"],
    ["ALT", "ALT", "Altlayer"],
    ["PENDLE", "PENDLE", "Pendle"],
    ["DOGINME", "DOGINME", "doginme"],
    ["KEYCAT", "KEYCAT", "Keyboard Cat"],
    ["EDGE", "EDGE", "Definitive"],
    ["PROMPT", "PROMPT", "Wayfinder"],
    ["KERNEL", "KERNEL", "KernelDAO"],
    ["RSR", "RSR", "Reserve Rights"],
    ["CLANKER", "CLANKER", "tokenbot"],
    ["ZORA", "ZORA", "Zora"],
    ["WLD", "WLD", "Worldcoin"],
    ["MANTLE", "MANTLE", "Mantle"],
    ["PAXG", "PAXG", "PAX Gold"],
    ["SXT", "SXT", "Space and Time"],
    ["LA", "LA", "Lagrange"],
    ["ENA", "ENA", "Ethena"],
    ["HOME", "HOME", "Defi App"],
    ["FARTCOIN", "FARTCOIN", "Fartcoin"],
    ["SQD", "SQD", "Subsquid"],
    ["CAKE", "CAKE", "PancakeSwap"],
    ["SPK", "SPK", "Spark"],
    ["S", "S", "Sonic"],
    ["NEWT", "NEWT", "Newton"],
    ["W", "W", "Wormhole"],
    ["USDS", "USDS", "USDS"],
    ["SKY", "SKY", "Sky"],
    ["PUMP", "PUMP", "Pump.fun"],
    ["ERA", "ERA", "Caldera"],
    ["JITOSOL", "JITOSOL", "Jito Staked SOL"],
    ["MPLX", "MPLX", "Metaplex"],
    ["TREE", "TREE", "Treehouse"],
    ["BNKR", "BNKR", "BankrCoin"],
    ["BIO", "BIO", "Bio Protocol"],
    ["RSC", "RSC", "ResearchCoin"],
    ["PROVE", "PROVE", "Succinct"],
    ["TOWNS", "TOWNS", "Towns Protocol"],
    ["MAMO", "MAMO", "Mamo"],
    ["EUL", "EUL", "Euler"],
    ["COSMOSDYDX", "COSMOSDYDX", "DYDX"],
    ["WCT", "WCT", "WalletConnect Token"],
    ["USELESS", "USELESS", "Useless Coin"],
    ["SAPIEN", "SAPIEN", "Sapien"],
    ["USD1", "USD1", "World Liberty Financial USD"],
    ["WLFI", "WLFI", "World Liberty Financial"],
    ["FLOCK", "FLOCK", "Flock"],
    ["SPX", "SPX", "SPX6900"],
    ["AVNT", "AVNT", "Avantis"],
    ["LAYER", "LAYER", "Solayer"],
    ["KMNO", "KMNO", "Kamino"],
    ["DOLO", "DOLO", "Dolomite"],
    ["ZKC", "ZKC", "Boundless"],
    ["BARD", "BARD", "Lombard"],
    ["CFG", "CFG", "Centrifuge"],
    ["TROLL", "TROLL", "TROLL"],
    ["XAN", "XAN", "Anoma"],
    ["XSGD", "XSGD", "XSGD"],
    ["AUDD", "AUDD", "Australian Digital Dollar"],
    ["SYND", "SYND", "Syndicate"],
    ["NOICE", "NOICE", "Noice"],
    ["LINEA", "LINEA", "Linea"],
    ["YB", "YB", "Yield Basis"],
    ["RECALL", "RECALL", "Recall Network"],
    ["2Z", "2Z", "DoubleZero"],
    ["KTA", "KTA", "Keeta"],
    ["BNB", "BNB", "BNB"],
    ["APR", "APR", "aPriori"],
    ["MET", "MET", "Meteora"],
    ["DBR", "DBR", "deBridge"],
    ["KITE", "KITE", "Kite"],
    ["TRUST", "TRUST", "Intuition"],
    ["ALLO", "ALLO", "Allora"],
    ["NOM", "NOM", "Nomina"],
    ["SUP", "SUP", "Superfluid"],
    ["TON", "TON", "Toncoin"],
    ["ASTER", "ASTER", "Aster"],
    ["BOBBOB", "BOBBOB", "BOB (Build on Bitcoin)"],
    ["MON", "MON", "Monad"],
    ["WMTX", "WMTX", "World Mobile Token"],
    ["FLUID", "FLUID", "Fluid"],
    ["IRYS", "IRYS", "Irys"],
    ["RLS", "RLS", "Rayls"],
    ["XPL", "XPL", "Plasma"],
    ["JUPITER", "JUPITER", "Jupiter"],
    ["WET", "WET", "Humidifi"],
    ["PLUME", "PLUME", "Plume"],
    ["HYPER", "HYPER", "Hyperlane"],
    ["BEAM", "BEAM", "Beam"],
    ["THQ", "THQ", "Theoriq"],
    ["ZKP", "ZKP", "zkPass"],
    ["BREV", "BREV", "Brevis"],
    ["RAY", "RAY", "Raydium"],
    ["LIGHTER", "LIGHTER", "Lighter"],
    ["FUN1", "FUN1", "Sport.fun"],
    ["ELSA", "ELSA", "Elsa"],
    ["SKR", "SKR", "Seeker"],
    ["FIGHT", "FIGHT", "FIGHT"],
    ["IMU", "IMU", "ImmuneFi"],
    ["SENT", "SENT", "Sentient"],
    ["BIRB", "BIRB", "Moonbirds"],
    ["INX", "INX", "Infinex"],
    ["ZAMA", "ZAMA", "Zama"],
    ["TRIA", "TRIA", "TRIA"],
    ["DOOD", "DOOD", "Doodles"],
    ["RNBW", "RNBW", "Rainbow"],
    ["HYPE", "HYPE", "Hyperliquid"],
    ["UP", "UP", "Superform"],
    ["DEEP", "DEEP", "DeepBook"],
    ["RAVE", "RAVE", "RaveDAO"],
    ["WAL", "WAL", "Walrus"],
    ["AZTEC", "AZTEC", "Aztec"],
    ["ESP", "ESP", "Espresso"],
    ["GWEI", "GWEI", "ETHGas"],
    ["ROBO", "ROBO", "Fabric Protocol"],
    ["OPN", "OPN", "OPINION"],
    ["LMTS", "LMTS", "Limitless"],
    ["AED", "AED", "United Arab Emirates Dirham"],
    ["AFN", "AFN", "Afghan Afghani"],
    ["ALL", "ALL", "Albanian Lek"],
    ["AMD", "AMD", "Armenian Dram"],
    ["ANG", "ANG", "Netherlands Antillean Gulden"],
    ["AOA", "AOA", "Angolan Kwanza"],
    ["ARS", "ARS", "Argentine Peso"],
    ["AUD", "AUD", "Australian Dollar"],
    ["AWG", "AWG", "Aruban Florin"],
    ["AZN", "AZN", "Azerbaijani Manat"],
    ["BAM", "BAM", "Bosnia and Herzegovina Convertible Mark"],
    ["BBD", "BBD", "Barbadian Dollar"],
    ["BDT", "BDT", "Bangladeshi Taka"],
    ["BGN", "BGN", "Bulgarian Lev"],
    ["BHD", "BHD", "Bahraini Dinar"],
    ["BIF", "BIF", "Burundian Franc"],
    ["BMD", "BMD", "Bermudian Dollar"],
    ["BND", "BND", "Brunei Dollar"],
    ["BOB", "BOB", "Bolivian Boliviano"],
    ["BRL", "BRL", "Real"],
    ["BSD", "BSD", "Bahamian Dollar"],
    ["BTN", "BTN", "Bhutanese Ngultrum"],
    ["BWP", "BWP", "Botswana Pula"],
    ["BYN", "BYN", "Belarusian Ruble"],
    ["BZD", "BZD", "Belize Dollar"],
    ["CAD", "CAD", "Canadian Dollar"],
    ["CDF", "CDF", "Congolese Franc"],
    ["CHF", "CHF", "Swiss Franc"],
    ["CLP", "CLP", "Chilean Peso"],
    ["CNY", "CNY", "Chinese Renminbi Yuan"],
    ["COP", "COP", "Colombian Peso"],
    ["CRC", "CRC", "Costa Rican Col\u00f3n"],
    ["CUP", "CUP", "Cuban Peso"],
    ["CVE", "CVE", "Cape Verdean Escudo"],
    ["CZK", "CZK", "Czech Koruna"],
    ["DJF", "DJF", "Djiboutian Franc"],
    ["DKK", "DKK", "Danish Krone"],
    ["DOP", "DOP", "Dominican Peso"],
    ["DZD", "DZD", "Algerian Dinar"],
    ["EGP", "EGP", "Egyptian Pound"],
    ["ETB", "ETB", "Ethiopian Birr"],
    ["EUR", "EUR", "Euro"],
    ["FJD", "FJD", "Fijian Dollar"],
    ["FKP", "FKP", "Falkland Pound"],
    ["GBP", "GBP", "British Pound"],
    ["GEL", "GEL", "Georgian Lari"],
    ["GHS", "GHS", "Ghanaian Cedi"],
    ["GIP", "GIP", "Gibraltar Pound"],
    ["GMD", "GMD", "Gambian Dalasi"],
    ["GNF", "GNF", "Guinean Franc"],
    ["GTQ", "GTQ", "Guatemalan Quetzal"],
    ["GYD", "GYD", "Guyanese Dollar"],
    ["HKD", "HKD", "Hong Kong Dollar"],
    ["HNL", "HNL", "Honduran Lempira"],
    ["HRK", "HRK", "Croatian Kuna"],
    ["HTG", "HTG", "Haitian Gourde"],
    ["HUF", "HUF", "Hungarian Forint"],
    ["IDR", "IDR", "Indonesian Rupiah"],
    ["ILS", "ILS", "Israeli New Sheqel"],
    ["INR", "INR", "Indian Rupee"],
    ["IQD", "IQD", "Iraqi Dinar"],
    ["IRR", "IRR", "Iranian Rial"],
    ["ISK", "ISK", "Icelandic Kr\u00f3na"],
    ["JMD", "JMD", "Jamaican Dollar"],
    ["JOD", "JOD", "Jordanian Dinar"],
    ["JPY", "JPY", "Japanese Yen"],
    ["KES", "KES", "Kenyan Shilling"],
    ["KGS", "KGS", "Kyrgyzstani Som"],
    ["KHR", "KHR", "Cambodian Riel"],
    ["KMF", "KMF", "Comorian Franc"],
    ["KRW", "KRW", "South Korean Won"],
    ["KWD", "KWD", "Kuwaiti Dinar"],
    ["KYD", "KYD", "Cayman Islands Dollar"],
    ["KZT", "KZT", "Kazakhstani Tenge"],
    ["LAK", "LAK", "Lao Kip"],
    ["LBP", "LBP", "Lebanese Pound"],
    ["LKR", "LKR", "Sri Lankan Rupee"],
    ["LRD", "LRD", "Liberian Dollar"],
    ["LSL", "LSL", "Lesotho Loti"],
    ["LYD", "LYD", "Libyan Dinar"],
    ["MAD", "MAD", "Moroccan Dirham"],
    ["MDL", "MDL", "Moldovan Leu"],
    ["MGA", "MGA", "Malagasy Ariary"],
    ["MKD", "MKD", "Macedonian Denar"],
    ["MMK", "MMK", "Myanmar Kyat"],
    ["MNT", "MNT", "Mongolian T\u00f6gr\u00f6g"],
    ["MOP", "MOP", "Macanese Pataca"],
    ["MRU", "MRU", "Mauritanian Ouguiya"],
    ["MUR", "MUR", "Mauritian Rupee"],
    ["MVR", "MVR", "Maldivian Rufiyaa"],
    ["MWK", "MWK", "Malawian Kwacha"],
    ["MXN", "MXN", "Mexican Peso"],
    ["MYR", "MYR", "Malaysian Ringgit"],
    ["MZN", "MZN", "Mozambican Metical"],
    ["NAD", "NAD", "Namibian Dollar"],
    ["NGN", "NGN", "Nigerian Naira"],
    ["NIO", "NIO", "Nicaraguan C\u00f3rdoba"],
    ["NOK", "NOK", "Norwegian Krone"],
    ["NPR", "NPR", "Nepalese Rupee"],
    ["NZD", "NZD", "New Zealand Dollar"],
    ["OMR", "OMR", "Omani Rial"],
    ["PAB", "PAB", "Panamanian Balboa"],
    ["PEN", "PEN", "Peruvian Sol"],
    ["PGK", "PGK", "Papua New Guinean Kina"],
    ["PHP", "PHP", "Philippine Peso"],
    ["PKR", "PKR", "Pakistani Rupee"],
    ["PLN", "PLN", "Polish Z\u0142oty"],
    ["PYG", "PYG", "Paraguayan Guaran\u00ed"],
    ["QAR", "QAR", "Qatari Riyal"],
    ["RON", "RON", "Romanian Leu"],
    ["RSD", "RSD", "Serbian Dinar"],
    ["RUB", "RUB", "Russian Ruble"],
    ["RWF", "RWF", "Rwandan Franc"],
    ["SAR", "SAR", "Saudi Riyal"],
    ["SBD", "SBD", "Solomon Islands Dollar"],
    ["SCR", "SCR", "Seychellois Rupee"],
    ["SDG", "SDG", "Sudanese Pound"],
    ["SEK", "SEK", "Swedish Krona"],
    ["SGD", "SGD", "Singapore Dollar"],
    ["SHP", "SHP", "Saint Helenian Pound"],
    ["SOS", "SOS", "Somali Shilling"],
    ["SRD", "SRD", "Surinamese Dollar"],
    ["SVC", "SVC", "Salvadoran Col\u00f3n"],
    ["SYP", "SYP", "Syrian Pound"],
    ["SZL", "SZL", "Swazi Lilangeni"],
    ["THB", "THB", "Thai Baht"],
    ["TJS", "TJS", "Tajikistani Somoni"],
    ["TMT", "TMT", "Turkmenistani Manat"],
    ["TND", "TND", "Tunisian Dinar"],
    ["TOP", "TOP", "Tongan Pa\u02bbanga"],
    ["TRY", "TRY", "Turkish Lira"],
    ["TTD", "TTD", "Trinidad and Tobago Dollar"],
    ["TWD", "TWD", "New Taiwan Dollar"],
    ["TZS", "TZS", "Tanzanian Shilling"],
    ["UAH", "UAH", "Ukrainian Hryvnia"],
    ["UGX", "UGX", "Ugandan Shilling"],
    ["USD", "USD", "United States Dollar"],
    ["UYU", "UYU", "Uruguayan Peso"],
    ["UZS", "UZS", "Uzbekistan Som"],
    ["VES", "VES", "Venezuelan Bol\u00edvar Soberano"],
    ["VND", "VND", "Vietnamese \u0110\u1ed3ng"],
    ["VUV", "VUV", "Vanuatu Vatu"],
    ["WST", "WST", "Samoan Tala"],
    ["XAF", "XAF", "Central African Cfa Franc"],
    ["XCD", "XCD", "East Caribbean Dollar"],
    ["XOF", "XOF", "West African Cfa Franc"],
    ["XPF", "XPF", "Cfp Franc"],
    ["YER", "YER", "Yemeni Rial"],
    ["ZAR", "ZAR", "South African Rand"],
    ["ZMK", "ZMK", "Zambian Kwacha"],
    ["ZMW", "ZMW", "Zambian Kwacha"],
    ["ARSMEP", "ARSMEP", "Argentine Blue Dollar"],
    ["LTL", "LTL", "Lithuanian Litas"],
    ["MRO", "MRO", "Mauritanian Ouguiya"],
    ["ZWD", "ZWD", "Zimbabwean Dollar"],
    ["JEP", "JEP", "Jersey Pound"],
    ["GGP", "GGP", "Guernsey Pound"],
    ["IMP", "IMP", "Isle of Man Pound"],
]
